### PR TITLE
Remove BIND9

### PR DESCRIPTION
**Pull request by felixfontein**
Removes dependency on BIND9. Replaces it by a simple DNS server based on [dnslib.server](https://pypi.org/project/dnslib/).

Should really reduce the image size :)

### CODE REVIEW

**Comment by felixfontein** [comment]
This seems to half the container size.

**Comment by felixfontein** [comment]
I also tried to base it on `python:3.6-alpine`, but getting `pyOpenSSL` installed there is more complicated. I might try it somewhen later, but definitely not in the next two weeks...

**Comment by felixfontein** [comment]
Thanks for merging this!

**Comment by mattclay** [comment]
@felixfontein Thank you for contributing this. I've tagged the 1.1.0 release. The new image is *much* smaller, going from 388.4 MB to 63.6 MB.

**Comment by felixfontein** [comment]
Perfect! I guess there's still some room for optimization, but for now it's pretty good ;-)

**Pull request merged**
