### PR TITLE
Add support for IP certificates

### PR DESCRIPTION
**Pull request by felixfontein**
Now that letsencrypt/pebble#221 has finally be merged, add changes from felixfontein/ansible-acme-test#1 so I can add proper integration tests for IP certificates to Ansible's acme_certificate tests (similar as in felixfontein/ansible-acme-test#1).

### CODE REVIEW

**Review by mattclay — APPROVED** [review]

**Comment by mattclay** [comment]
@felixfontein Did verify the existing tests pass when run against a locally built version of the container with these changes?

**Comment by felixfontein** [comment]
I'm still in the process of doing that, and got interrupted and forgot that didn't finish yet :) I'll ping you once it's done!

**Comment by felixfontein** [comment]
@mattclay there's a little bug in the current Pebble master, I'll update this PR once it is fixed.

About the existing tests: they won't work, since I had to adjust the controller's API a bit. When bumping the test container version in https://github.com/ansible/ansible, I'll have to include similar changes as in felixfontein/ansible-acme-test#1 to the tests to adjust the calls.

**Comment by mattclay** [comment]
@felixfontein OK, sounds good. Let me know when this PR is ready so I can merge and publish a new release.

**Comment by felixfontein** [comment]
This now includes two bugfixes (letsencrypt/pebble#237, letsencrypt/pebble#238), with which it should work. I'll run some tests...

**Comment by felixfontein** [comment]
Tests are running through with https://github.com/ansible/ansible/compare/devel...felixfontein:acme-test-container-upgrade (I've tentatively named the container 1.5.0; bumping the middle version should be ok since the API changed a little.)

**Comment by felixfontein** [comment]
@mattclay this PR is now ready!

**Comment by mattclay** [comment]
@felixfontein Thanks. Merged and released as 1.5.0.

**Comment by felixfontein** [comment]
@mattclay thanks for handling this!

**Pull request merged**
