### PR TITLE
Initial Shippable support.

### PR DESCRIPTION
**Pull request by mattclay**

### CODE REVIEW

**Comment by mattclay** [comment]
Building the docker image requires a newer Docker server version than available in our standard node pool. Verified working with the newer test_node_pool.

**Comment by mattclay** [comment]
Temporarily disabled Shippable on this repo until a permanent node is available.

**Comment by felixfontein** [comment]
@mattclay Is that because of the two-step build process?

**Comment by mattclay** [comment]
@felixfontein Yes. It's not a problem for quay.io to build the images, but Shippable can't test these PRs until we switch to newer machine images, or stop using two-step builds. We need to switch to the newer machine images eventually, but there are other issues to address before we do that.

**Comment by mattclay** [comment]
Closing for now. This can be revisited once we've upgraded our Shippable nodes.

**Pull request closed without merging**
